path_classifiers:
  library:
    - tools
  generated:
    # The exports defined in __init__.py are defined in the Cython module
    # np.random.mtrand. By excluding this file we suppress a number of
    # "undefined export" alerts
    - numpy/random/__init__.py

extraction:
  python:
    python_setup:
        requirements:
          - cython>=0.29
  cpp:
    index:
      build_command:
        - python3 setup.py build

queries:
  - include: py/file-not-closed
