language: python

dist: xenial
services:
  - xvfb

env:
  global:
  - GH_REPO: github.com/data-8/datascience.git
  - secure: "qnq+fVBiLA2MtG+/e/AndJlI12mteQtW9oikGi7wHGXKuy1JEE5lVh9kM6SRNHJPX7zVg/SB43nne65bSd4/PADWXxfx05tn90KmwA1lo0C1lRSija8OfJpsR5diJrY8hRs3jePp2m61tsqmWOn+bo1EFVj4P/z9U/4xp/snCk6/vw1Q3Hxtk2JzYrW1FxEbG+xXIepUpXeYmB4hjHtkCAqKnJpGiDSlQkJy7zWKfUvyzp9L3LZIPfWLg91asvrqc3o+TdVdqfM+CRdhdSHgqD4cp2dcaH94fy8wFWHf5XVCf4ZlBWrT1NjyTqN52lF/HcnHzORQhBCDk0wiD/kfZ+/7KWVp3lsE2/QVCc5dE1jdfO0h5cbqQgzdNA5gdiCIMoA39LARlX1+CkkQJlQ/6R4GsYtoBut1yiS6GhKhXs0Dnmd3DNLxleRfdKIkIM9ilBhb1fuDQaeRLJIr8wDfzigeZ3QHp29iKXgRRWD6bwbD7PiLYxnJs0NIaa9xu5rvV/4Q/DwYXyOjBzWdoJX9u+pDjVcZxva6Dj8l7zUSG5QCiYm3SQekKOegorBbcQdkHMOwyx+CVUYfeazAbQryJzAacmCH3Gvoc1q2wD3n5P9NzHj/V+/Llh8O1MzeHxDzflgf2bVsHpaOUl/cyNaJ3nldGCktgLP6XZ6DI1o1PWU="
sudo: false

python:
  - "3.6"

cache:
  apt: true
  directories:
    - $HOME/miniconda

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -f -p $HOME/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

install:
  - conda env update -f linux_environment.yml
  - source activate datascience
  - python3 setup.py install

script:
  - coverage run setup.py test

after_success:
  - coveralls
  - bash tools/deploy_docs.sh
